// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cookie = {
  name: string;
  value: string;
  domain: CookieDomain;
  expires: CookieExpires;
  path: string;
  secure: boolean;
  httpOnly: boolean;
  sameSite: CookieSameSite | null;
};

export type CookieDomain = { HostOnly: string } | { Suffix: string } | "NotPresent" | "Empty";

export type CookieExpires = { AtUtc: string } | "SessionEnd";

export type CookieSameSite = "Strict" | "Lax" | "None";

export type HttpRequest = {
  model: "http_request";
  id: string;
  createdAt: string;
  updatedAt: string;
  workspaceId: string;
  folderId: string | null;
  authentication: Record<string, any>;
  authenticationType: string | null;
  body: Record<string, any>;
  bodyType: string | null;
  description: string;
  headers: Array<HttpRequestHeader>;
  method: string;
  name: string;
  sortPriority: number;
  url: string;
  /**
   * URL parameters used for both path placeholders (`:id`) and query string entries.
   */
  urlParameters: Array<HttpUrlParameter>;
  settingSendCookies: InheritedBoolSetting;
  settingStoreCookies: InheritedBoolSetting;
  settingValidateCertificates: InheritedBoolSetting;
  settingFollowRedirects: InheritedBoolSetting;
  settingRequestTimeout: InheritedIntSetting;
};

export type HttpRequestHeader = { enabled?: boolean; name: string; value: string; id?: string };

/**
 * Serializable representation of HTTP response events for DB storage.
 * This mirrors `yaak_http::sender::HttpResponseEvent` but with serde support.
 * The `From` impl is in yaak-http to avoid circular dependencies.
 */
export type HttpResponseEventData =
  | {
      type: "setting";
      name: string;
      value: string;
      source_model?: string;
      source_id?: string;
      source_name?: string;
    }
  | { type: "info"; message: string }
  | {
      type: "redirect";
      url: string;
      status: number;
      behavior: string;
      dropped_body: boolean;
      dropped_headers: Array<string>;
    }
  | {
      type: "send_url";
      method: string;
      scheme: string;
      username: string;
      password: string;
      host: string;
      port: number;
      path: string;
      query: string;
      fragment: string;
    }
  | { type: "receive_url"; version: string; status: string }
  | { type: "header_up"; name: string; value: string }
  | { type: "header_down"; name: string; value: string }
  | { type: "chunk_sent"; bytes: number }
  | { type: "chunk_received"; bytes: number }
  | {
      type: "dns_resolved";
      hostname: string;
      addresses: Array<string>;
      duration: bigint;
      overridden: boolean;
    };

export type HttpResponseHeader = { name: string; value: string };

/**
 * The resolved send settings, values only: what an executor has to obey, with the sources
 * (which model each came from) left behind in [`ResolvedHttpRequestSettings`]. This is what
 * crosses from a tab to the Yaak server, and what the server reads.
 */
export type HttpSendSettings = {
  validateCertificates: boolean;
  followRedirects: boolean;
  /**
   * Milliseconds. Zero or negative means no timeout.
   */
  timeoutMs: number;
  sendCookies: boolean;
  storeCookies: boolean;
};

export type HttpUrlParameter = {
  enabled?: boolean;
  /**
   * Colon-prefixed parameters are treated as path parameters if they match, like `/users/:id`
   * Other entries are appended as query parameters
   */
  name: string;
  value: string;
  id?: string;
};

export type InheritedBoolSetting = { enabled?: boolean; value: boolean };

export type InheritedIntSetting = { enabled?: boolean; value: number };
