// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelChangeEvent } from "./ModelChangeEvent";

export type HttpExchange = {
  id: string;
  createdAt: string;
  updatedAt: string;
  url: string;
  method: string;
  reqHeaders: Array<ProxyHeader>;
  reqBody: Array<number> | null;
  resStatus: number | null;
  resHeaders: Array<ProxyHeader>;
  resBody: Array<number> | null;
  error: string | null;
};

export type ModelPayload = { model: HttpExchange; change: ModelChangeEvent };

export type ProxyHeader = { name: string; value: string };
