// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder, GrpcRequest, HttpRequest, WebsocketRequest, Workspace } from "./gen_models";

export type CallFolderActionArgs = { folder: Folder };

export type CallFolderActionRequest = {
  index: number;
  pluginRefId: string;
  args: CallFolderActionArgs;
};

export type CallGrpcRequestActionArgs = { grpcRequest: GrpcRequest; protoFiles: Array<string> };

export type CallGrpcRequestActionRequest = {
  index: number;
  pluginRefId: string;
  args: CallGrpcRequestActionArgs;
};

export type CallHttpRequestActionArgs = { httpRequest: HttpRequest };

export type CallHttpRequestActionRequest = {
  index: number;
  pluginRefId: string;
  args: CallHttpRequestActionArgs;
};

export type CallWebsocketRequestActionArgs = { websocketRequest: WebsocketRequest };

export type CallWebsocketRequestActionRequest = {
  index: number;
  pluginRefId: string;
  args: CallWebsocketRequestActionArgs;
};

export type CallWorkspaceActionArgs = { workspace: Workspace };

export type CallWorkspaceActionRequest = {
  index: number;
  pluginRefId: string;
  args: CallWorkspaceActionArgs;
};

export type Color = "primary" | "secondary" | "info" | "success" | "notice" | "warning" | "danger";

export type CompletionOptionType = "constant" | "variable";

export type EditorLanguage =
  | "text"
  | "javascript"
  | "json"
  | "html"
  | "xml"
  | "graphql"
  | "markdown"
  | "c"
  | "clojure"
  | "csharp"
  | "go"
  | "http"
  | "java"
  | "kotlin"
  | "objective_c"
  | "ocaml"
  | "php"
  | "powershell"
  | "python"
  | "r"
  | "ruby"
  | "shell"
  | "swift";

export type FileFilter = {
  name: string;
  /**
   * File extensions to require
   */
  extensions: Array<string>;
};

export type FilterResponse = { content: string; error?: string };

export type FolderAction = { label: string; icon?: Icon };

export type FormInput =
  | ({ type: "text" } & FormInputText)
  | ({ type: "editor" } & FormInputEditor)
  | ({ type: "select" } & FormInputSelect)
  | ({ type: "checkbox" } & FormInputCheckbox)
  | ({ type: "file" } & FormInputFile)
  | ({ type: "http_request" } & FormInputHttpRequest)
  | ({ type: "accordion" } & FormInputAccordion)
  | ({ type: "h_stack" } & FormInputHStack)
  | ({ type: "banner" } & FormInputBanner)
  | ({ type: "markdown" } & FormInputMarkdown)
  | ({ type: "key_value" } & FormInputKeyValue);

export type FormInputAccordion = { label: string; inputs?: Array<FormInput>; hidden?: boolean };

export type FormInputBanner = { inputs?: Array<FormInput>; hidden?: boolean; color?: Color };

export type FormInputCheckbox = {
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputEditor = {
  /**
   * Placeholder for the text input
   */
  placeholder?: string | null;
  /**
   * Don't show the editor gutter (line numbers, folds, etc.)
   */
  hideGutter?: boolean;
  /**
   * Language for syntax highlighting
   */
  language?: EditorLanguage;
  readOnly?: boolean;
  /**
   * Fixed number of visible rows
   */
  rows?: number;
  completionOptions?: Array<GenericCompletionOption>;
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputFile = {
  /**
   * The title of the file selection window
   */
  title: string;
  /**
   * Allow selecting multiple files
   */
  multiple?: boolean;
  directory?: boolean;
  defaultPath?: string;
  filters?: Array<FileFilter>;
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputHStack = { inputs?: Array<FormInput>; hidden?: boolean };

export type FormInputHttpRequest = {
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputKeyValue = {
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputMarkdown = { content: string; hidden?: boolean };

export type FormInputSelect = {
  /**
   * The options that will be available in the select input
   */
  options: Array<FormInputSelectOption>;
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type FormInputSelectOption = { label: string; value: string };

export type FormInputText = {
  /**
   * Placeholder for the text input
   */
  placeholder?: string | null;
  /**
   * Placeholder for the text input
   */
  password?: boolean;
  /**
   * Whether to allow newlines in the input, like a <textarea/>
   */
  multiLine?: boolean;
  completionOptions?: Array<GenericCompletionOption>;
  /**
   * The name of the input. The value will be stored at this object attribute in the resulting data
   */
  name: string;
  /**
   * Whether this input is visible for the given configuration. Use this to
   * make branching forms.
   */
  hidden?: boolean;
  /**
   * Whether the user must fill in the argument
   */
  optional?: boolean;
  /**
   * The label of the input
   */
  label?: string;
  /**
   * Visually hide the label of the input
   */
  hideLabel?: boolean;
  /**
   * The default value
   */
  defaultValue?: string;
  disabled?: boolean;
  /**
   * Longer description of the input, likely shown in a tooltip
   */
  description?: string;
};

export type GenericCompletionOption = {
  label: string;
  detail?: string;
  info?: string;
  type?: CompletionOptionType;
  boost?: number;
};

export type GetFolderActionsResponse = { actions: Array<FolderAction>; pluginRefId: string };

export type GetGrpcRequestActionsResponse = {
  actions: Array<GrpcRequestAction>;
  pluginRefId: string;
};

export type GetHttpAuthenticationConfigResponse = {
  args: Array<FormInput>;
  pluginRefId: string;
  actions?: Array<HttpAuthenticationAction>;
};

export type GetHttpAuthenticationSummaryResponse = {
  name: string;
  label: string;
  shortLabel: string;
};

export type GetHttpRequestActionsResponse = {
  actions: Array<HttpRequestAction>;
  pluginRefId: string;
};

export type GetTemplateFunctionConfigResponse = { function: TemplateFunction; pluginRefId: string };

export type GetTemplateFunctionSummaryResponse = {
  functions: Array<TemplateFunction>;
  pluginRefId: string;
};

export type GetThemesResponse = { themes: Array<Theme> };

export type GetWebsocketRequestActionsResponse = {
  actions: Array<WebsocketRequestAction>;
  pluginRefId: string;
};

export type GetWorkspaceActionsResponse = { actions: Array<WorkspaceAction>; pluginRefId: string };

export type GrpcRequestAction = { label: string; icon?: Icon };

export type HttpAuthenticationAction = { label: string; icon?: Icon };

export type HttpRequestAction = { label: string; icon?: Icon };

export type Icon =
  | "alert_triangle"
  | "check"
  | "check_circle"
  | "chevron_down"
  | "copy"
  | "info"
  | "pin"
  | "search"
  | "trash"
  | "_unknown";

export type JsonPrimitive = string | number | boolean | null;

export type RenderPurpose = "send" | "preview";

export type TemplateFunction = {
  name: string;
  previewType?: TemplateFunctionPreviewType;
  description?: string;
  /**
   * Also support alternative names. This is useful for not breaking existing
   * tags when changing the `name` property
   */
  aliases?: Array<string>;
  args: Array<TemplateFunctionArg>;
  /**
   * A list of arg names to show in the inline preview. If not provided, none will be shown (for privacy reasons).
   */
  previewArgs?: Array<string>;
};

/**
 * Similar to FormInput, but contains
 */
export type TemplateFunctionArg = FormInput;

export type TemplateFunctionPreviewType = "live" | "click" | "none";

export type Theme = {
  /**
   * How the theme is identified. This should never be changed
   */
  id: string;
  /**
   * The friendly name of the theme to be displayed to the user
   */
  label: string;
  /**
   * Whether the theme will be used for dark or light appearance
   */
  dark: boolean;
  /**
   * The default top-level colors for the theme
   */
  base: ThemeComponentColors;
  /**
   * Optionally override theme for individual UI components for more control
   */
  components?: ThemeComponents;
};

export type ThemeComponentColors = {
  surface?: string;
  surfaceHighlight?: string;
  surfaceActive?: string;
  text?: string;
  textSubtle?: string;
  textSubtlest?: string;
  border?: string;
  borderSubtle?: string;
  borderFocus?: string;
  shadow?: string;
  backdrop?: string;
  selection?: string;
  primary?: string;
  secondary?: string;
  info?: string;
  success?: string;
  notice?: string;
  warning?: string;
  danger?: string;
};

export type ThemeComponents = {
  dialog?: ThemeComponentColors;
  menu?: ThemeComponentColors;
  toast?: ThemeComponentColors;
  sidebar?: ThemeComponentColors;
  responsePane?: ThemeComponentColors;
  appHeader?: ThemeComponentColors;
  button?: ThemeComponentColors;
  banner?: ThemeComponentColors;
  templateTag?: ThemeComponentColors;
  urlBar?: ThemeComponentColors;
  editor?: ThemeComponentColors;
  input?: ThemeComponentColors;
};

export type WebsocketRequestAction = { label: string; icon?: Icon };

export type WorkspaceAction = { label: string; icon?: Icon };
