// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MethodDefinition = {
  name: string;
  schema: string;
  clientStreaming: boolean;
  serverStreaming: boolean;
};

export type ServiceDefinition = { name: string; methods: Array<MethodDefinition> };
